# Generated by Django 4.2.3 on 2023-07-11 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teloEnvio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='direcciones',
            old_name='idEmpresa',
            new_name='idCliente',
        ),
        migrations.RenameField(
            model_name='pedidos',
            old_name='idEmpresa',
            new_name='idCliente',
        ),
    ]
